sudo: required
dist: trusty
jdk:
- openjdk11
script:
- mvn clean install
- mvn sonar:sonar
- heroku login
- mvn clean heroku:deploy-war
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - addons:
      sonarcloud:
        organization: "vitaliitkachuk"
        token:
          secure: "**************************" # encrypted value of your token

    script:
      # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar