sudo: required
dist: trusty
jdk:
- openjdk11
deploy:
  provider: heroku
  api_key:
    secure: "8dffeee5-4941-473f-9dc4-f134817baf02"
  app: java-project-template-vt
script:
- mvn clean install -Djacoco.skip=true
- mvn sonar:sonar
- mvn clean heroku:deploy-war
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - addons:
      sonarcloud:
        organization: "vitaliitkachuk"
        token:
          secure: "**************************" # encrypted value of your token

    script:
      # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar